# Generated by Django 3.0.5 on 2020-05-01 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gkapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='cake_info',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_image', models.ImageField(upload_to='img/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gkapp.Cake')),
            ],
        ),
    ]
