# Generated by Django 3.0.5 on 2020-05-01 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gkapp', '0002_auto_20200501_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='cake_info',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gkapp.Cake'),
        ),
    ]
