# Generated by Django 3.0.2 on 2020-05-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gkapp', '0005_auto_20200501_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='cake_info',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cake',
            name='cake_name',
            field=models.CharField(max_length=9),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
